pipeline:
  name: package
  enabled: true
  with:
    tools.directory: $PIPELINER_HOME/tools
    output.directory: OUTPUT
    temp.directory: TEMP
  jobs:
    - name: package
      enabled: true
      steps:
        - name: clean output directory
          enabled: true
          run: rm -Rf ${{ output.directory }}/*
        - name: execute tests
          enabled: true
          run: ./pipeliner tests/all.yaml
        - name: execute examples
          enabled: true
          run: ./pipeliner examples/all.yaml
        - name: create output directory
          enabled: true
          run: mkdir -p ${{ output.directory }}/.pipeliner
        - name: copy jar
          enabled: true
          run: cp target/verifyica-pipeliner.jar ${{ output.directory }}/.pipeliner
        - name: copy hello world pipeline
          enabled: true
          run: cp examples/hello-world-pipeline.yaml ${{ output.directory }}/.pipeliner
        - name: copy pipeliner shell script
          enabled: true
          run: cp pipeliner ${{ output.directory }}/
        - name: generate sha1 checksums (phase 1)
          enabled: true
          working-directory: ${{ output.directory }}
          run: ${{ tools.directory }}/generate-sha1-checksums.sh .
        - name: generate sha1 checksums (phase 2)
          enabled: true
          working-directory: ${{ output.directory }}/.pipeliner
          run: ${{ tools.directory }}/generate-sha1-checksums.sh .
        - name: install zip
          enabled: false
          run: sudo apt-get install -y zip
        - name: create zip package
          enabled: true
          working-directory: ${{ output.directory }}
          run: zip -qr verifyica-pipeliner.zip * .*
        - name: create zip package checksums
          working-directory: ${{ output.directory }}
          run: sha1sum verifyica-pipeliner.zip | awk '{print $1}' > verifyica-pipeliner.zip.sha1
        - name: unzip zip package
          working-directory: ${{ output.directory }}
          run: unzip -q verifyica-pipeliner.zip -d ${{ temp.directory }}
        - name: create tar.gz package
          working-directory: ${{ output.directory }}
          run: tar -czf verifyica-pipeliner.tar.gz -C ${{ temp.directory }} .
        - name: create tar.gz package checksums
          working-directory: ${{ output.directory }}
          run: sha1sum verifyica-pipeliner.tar.gz | awk '{print $1}' > verifyica-pipeliner.tar.gz.sha1
        - name: cleanup output directory
          enabled: true
          working-directory: ${{ output.directory }}
          run: |
            rm -Rf .pipeliner
            rm -Rf ${{ temp.directory }}/*
            rm -Rf ${{ temp.directory }}/.*
        - name: create temp directory
          enabled: true
          working-directory: ${{ output.directory }}/${{ temp.directory }}
          run: mkdir -p tar-gz-tmp
        - name: extract tar.gz package
          enabled: true
          working-directory: ${{ output.directory }}/${{ temp.directory }}/tar-gz-tmp
          run: tar -xf ../../verifyica-pipeliner.tar.gz
        - name: create temp directory
          enabled: true
          working-directory: ${{ output.directory }}/${{ temp.directory }}
          run: mkdir -p zip-tmp
        - name: extract zip package
          enabled: true
          working-directory: ${{ output.directory }}/${{ temp.directory }}/zip-tmp
          run: unzip -q ../../verifyica-pipeliner.zip
        - name: validate package contents
          enabled: true
          working-directory: ${{ output.directory }}/${{ temp.directory }}
          run: diff -r tar-gz-tmp zip-tmp
        - name: cleanup temp directory
          enabled: true
          working-directory: ${{ output.directory }}
          run: rm -Rf ${{ temp.directory }}
