pipeline:
  name: regression-build
  properties:
    - name: global.property
      value: Global Property - Pipeline
    - name: pipeline.directory
      value: .
    - name: pipeline.property
      value: Pipeline Property
  jobs:
    - name: phase-1
      enabled: true
      steps:
        - name: step-1
          enabled: true
          directory: '{{pipeline.directory}}'
          command: ./mvnw clean package
    - name: phase-2
      enabled: true
      properties:
        - name: job.property
          value: Job Property
        - name: global.property
          value: Global Property - Job
      steps:
        - name: step-1
          enabled: true
          directory: "{{pipeline.directory}}"
          command: 'echo.sh {{USER}}'
        - name: echo-pipeline-property
          enabled: true
          command: 'echo {{pipeline.property}}'
        - name: echo-job-property
          enabled: true
          command: 'echo {{job.property}}'
        - name: echo-step-property
          enabled: true
          properties:
            - name: step.property
              value: Step Property
            - name: x.global.property
              value: Global Property - Step
          command: 'echo.sh "{{step.property}}" "{{global.property}}"'

