#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $(basename "$0") <pipeline.yaml> [pipeline2.yaml...]"
    exit 1
fi

JAR_PATH="target/verifyica-pipelines-0.0.1.jar"

if [ ! -f "$JAR_PATH" ]; then
    JAR_PATH="verifyica-pipelines-0.0.1.jar"
fi

if [ ! -f "$JAR_PATH" ]; then
     JAR_PATH=".verifyica-pipelines/verifyica-pipelines-0.0.1.jar"
fi

if [ ! -f "$JAR_PATH" ]; then
     JAR_PATH=".verifyica/verifyica-pipelines-0.0.1.jar"
fi

if [ ! -f "$JAR_PATH" ]; then
    echo "verifyica-pipelines-0.0.1.jar not found"
    exit 1
fi

java -jar "${JAR_PATH}" "$@"
