pipeline:
  id: regression-build
  property:
    - name: pipeline.directory
      value: .
  job:
    - id: phase-1
      enabled: true
      step:
        - id: step-1
          workingDirectory: '{{pipeline.directory}}'
          command: ./mvnw clean package
    - id: phase-2
      enabled: true
      step:
        - id: step-1
          enabled: true
          workingDirectory: "{{pipeline.directory}}"
          command: './test.sh {{USER}}'
