pipeline:
  id: regression-build
  property:
    - name: global.property
      value: Global Property - Pipeline
    - name: pipeline.directory
      value: .
    - name: pipeline.property
      value: Pipeline Property
  job:
    - id: phase-1
      enabled: true
      step:
        - id: step-1
          enabled: true
          directory: '{{pipeline.directory}}'
          command: ./mvnw clean package
    - id: phase-2
      enabled: true
      property:
        - name: job.property
          value: Job Property
        - name: global.property
          value: Global Property - Job
      step:
        - id: step-1
          enabled: true
          directory: "{{pipeline.directory}}"
          command: 'echo.sh {{USER}}'
        - id: echo-pipeline-property
          enabled: true
          command: 'echo {{pipeline.property}}'
        - id: echo-job-property
          enabled: true
          command: 'echo {{job.property}}'
        - id: echo-step-property
          enabled: true
          property:
            - name: step.property
              value: Step Property
            - name: x.global.property
              value: Global Property - Step
          command: 'echo.sh "{{step.property}}" "{{global.property}}"'

