pipeline:
  name: release
  enabled: true
  with:
    VERSION: 0.4.0
  jobs:
    - name: release
      enabled: true
      steps:
        - name: change version
          enabled: true
          run: |
            ./mvnw versions:set -DnewVersion="${{ INPUT_VERSION }}" -DprocessAllModules >> /dev/null
            rm -Rf $(find . -name "*versionsBackup")
        - name: package
          enabled: true
          run: ./pipeliner package.yaml
        - name: commit version
          enabled: true
          run: |
            git add -u
            git commit -s -m "Prepare for release"
        - name: tag version
          run: |
            git tag "${{ INPUT_VERSION }}"
            git push --tags
        - name: checkout & push release branch
          run:
            git checkout -b "release-${{ INPUT_VERSION }}"
            git push --set-upstream origin "release-${{ INPUT_VERSION }}"
        - name: checkout main
          run: git checkout -b main
        - name: change version
          enabled: true
          run: |
            ./mvnw versions:set -DnewVersion="${{ INPUT_VERSION }}-post" -DprocessAllModules >> /dev/null
            rm -Rf $(find . -name "*versionsBackup")
        - name: commit version
          enabled: true
          run: |
            git add -u
            git commit -s -m "Prepare for development"