workflow:
  id: regression-build
  name: Regression Build
  property:
    - name: verifyica.directory
      value: /home/x/Development/github/verifyica-team/verifyica
    - name: pipeline.directory
      value: "{{PWD}}"
  job:
    - id: phase-1
      name: Phase 1
      enabled: true
      step:
        - id: step-1
          name: Update code
          workingDirectory: '{{verifyica.directory}}'
          command: git pull
        - id: step-2
          name: Build code
          workingDirectory: '{{verifyica.directory}}'
          command: ./mvnw clean package
    - id: phase-2
      name: Phase 2
      enabled: true
      step:
        - id: step-1
          name: Run test
          enabled: true
          workingDirectory: "{{pipeline.directory}}"
          command: './test.sh {{USER}} {{test.user}}'
