pipeline:
  name: Hello World Python Pipeline
  jobs:
    - name: Hello World Python Job
      working-directory: examples/ipc/python
      steps:
        - name: Hello World Python Step
          shell: none
          with:
            name: Test User
          run: python3 extension.py
        - name: Hello World Python Output Variables
          run: |
            echo output extension property \${{ extension_property_1 }} = "${{ extension_property_1 }}"
            echo output extension property \${{ extension_property_2 }} = "${{ extension_property_2 }}"
