pipeline:
  name: Hello World Lua Pipeline
  jobs:
    - name: Hello World Lua Job
      working-directory: examples/ipc/lua
      steps:
        - name: Hello World Lua Step
          shell: none
          with:
            name: Test User
          run: lua extension.lua
        - name: Hello World Lua Captured Variables
          run: |
            echo captured extension variable \${{ extension_variable_1 }} = "${{ extension_variable_1 }}"
            echo captured extension variable \${{ extension_variable_2 }} = "${{ extension_variable_2 }}"
