#
# Disabled by default
#
# Go may not be installed
# Groovy may not be installed
# Java is installed, but we disable it
# Node may not be installed
# Python may not be installed
# Rust may not be installed
#
pipeline:
  name: all
  enabled: false
  jobs:
    - name: all
      steps:
        - name: examples/ipc/go/go-extension.yaml
          run: $PIPELINER examples/ipc/go/go-extension.yaml
        - name: examples/ipc/groovy/groovy-extension.yaml
          run: $PIPELINER examples/ipc/groovy/groovy-extension.yaml
        - name: examples/ipc/java/java-extension.yaml
          run: $PIPELINER examples/ipc/java/java-extension.yaml
        - name: examples/ipc/js/js-extension.yaml
          run: $PIPELINER examples/ipc/js/js-extension.yaml
        - name: examples/ipc/kotlin/kotlin-extension.yaml
          run: $PIPELINER examples/ipc/kotlin/kotlin-extension.yaml
        - name: examples/ipc/python/python-extension.yaml
          run: $PIPELINER examples/ipc/python/python-extension.yaml
        - name: examples/ipc/rust/rust-extension.yaml
          run: $PIPELINER examples/ipc/rust/rust-extension.yaml
