#
# Disabled by default
#
# Bash is most likely installed, but we disable it
# C# may not be installed
# Go may not be installed
# Groovy may not be installed
# Java is installed, but we disable it
# Node may not be installed
# Kotlin may not be installed
# Lua may not be installed
# Nim may not be installed
# Python may not be installed
# Rust may not be installed
#
pipeline:
  name: all
  enabled: true
  jobs:
    - name: all
      steps:
        - name: examples/ipc/bash/bash-extension.yaml
          run: --pipeline examples/ipc/bash/bash-extension.yaml
        - name: examples/ipc/c#/c#-extension.yaml
          run: --pipeline examples/ipc/c#/c#-extension.yaml
        - name: examples/ipc/go/go-extension.yaml
          run: --pipeline examples/ipc/go/go-extension.yaml
        - name: examples/ipc/groovy/groovy-extension.yaml
          run: --pipeline examples/ipc/groovy/groovy-extension.yaml
        - name: examples/ipc/java/java-extension.yaml
          run: --pipeline examples/ipc/java/java-extension.yaml
        - name: examples/ipc/js/js-extension.yaml
          run: --pipeline examples/ipc/js/js-extension.yaml
        - name: examples/ipc/kotlin/kotlin-extension.yaml
          run: --pipeline examples/ipc/kotlin/kotlin-extension.yaml
        - name: examples/ipc/lua/lua-extension.yaml
          run: --pipeline examples/ipc/lua/lua-extension.yaml
        - name: examples/ipc/nim/nim-extension.yaml
          run: --pipeline examples/ipc/nim/nim-extension.yaml
        - name: examples/ipc/python/python-extension.yaml
          run: --pipeline examples/ipc/python/python-extension.yaml
        - name: examples/ipc/rust/rust-extension.yaml
          run: --pipeline examples/ipc/rust/rust-extension.yaml
        - name: echo extension properties
          run: |
            echo output extension variable \${{ bash_extension_variable_1 }} = "${{ bash_extension_variable_1 }}"
            echo output extension variable \${{ bash_extension_variable_2 }} = "${{ bash_extension_variable_2 }}"
            echo output extension variable \${{ csharp_extension_variable_1 }} = "${{ csharp_extension_variable_1 }}"
            echo output extension variable \${{ csharp_extension_variable_2 }} = "${{ csharp_extension_variable_2 }}"
            echo output extension variable \${{ go_extension_variable_1 }} = "${{ go_extension_variable_1 }}"
            echo output extension variable \${{ go_extension_variable_2 }} = "${{ go_extension_variable_2 }}"
            echo output extension variable \${{ groovy_extension_variable_1 }} = "${{ groovy_extension_variable_1 }}"
            echo output extension variable \${{ groovy_extension_variable_2 }} = "${{ groovy_extension_variable_2 }}"
            echo output extension variable \${{ java_extension_variable_1 }} = "${{ java_extension_variable_1 }}"
            echo output extension variable \${{ java_extension_variable_2 }} = "${{ java_extension_variable_2 }}"
            echo output extension variable \${{ js_extension_variable_1 }} = "${{ js_extension_variable_1 }}"
            echo output extension variable \${{ js_extension_variable_2 }} = "${{ js_extension_variable_2 }}"
            echo output extension variable \${{ kotlin_extension_variable_1 }} = "${{ kotlin_extension_variable_1 }}"
            echo output extension variable \${{ kotlin_extension_variable_2 }} = "${{ kotlin_extension_variable_2 }}"
            echo output extension variable \${{ lua_extension_variable_1 }} = "${{ lua_extension_variable_1 }}"
            echo output extension variable \${{ lua_extension_variable_2 }} = "${{ lua_extension_variable_2 }}"
            echo output extension variable \${{ nim_extension_variable_1 }} = "${{ nim_extension_variable_1 }}"
            echo output extension variable \${{ nim_extension_variable_2 }} = "${{ nim_extension_variable_2 }}"
            echo output extension variable \${{ python_extension_variable_1 }} = "${{ python_extension_variable_1 }}"
            echo output extension variable \${{ python_extension_variable_2 }} = "${{ python_extension_variable_2 }}"
            echo output extension variable \${{ rust_extension_variable_1 }} = "${{ rust_extension_variable_1 }}"
            echo output extension variable \${{ rust_extension_variable_2 }} = "${{ rust_extension_variable_2 }}"