#
# Disabled by default
#
# Bash is most likely installed, but we disable it
# dotnet may not be installed
# Go may not be installed
# Groovy may not be installed
# Java is installed, but we disable it
# Node may not be installed
# Kotlin may not be installed
# Lua may not be installed
# Python may not be installed
# Rust may not be installed
#
pipeline:
  name: all
  enabled: false
  jobs:
    - name: all
      steps:
        - name: examples/ipc/bash/bash-extension.yaml
          capture-prefix: bash
          run: $PIPELINER examples/ipc/bash/bash-extension.yaml
        - name: examples/ipc/c#/c#-extension.yaml
          capture-prefix: csharp
          run: $PIPELINER examples/ipc/c#/c#-extension.yaml
        - name: examples/ipc/go/go-extension.yaml
          capture-prefix: go
          run: $PIPELINER examples/ipc/go/go-extension.yaml
        - name: examples/ipc/groovy/groovy-extension.yaml
          capture-prefix: groovy
          run: $PIPELINER examples/ipc/groovy/groovy-extension.yaml
        - name: examples/ipc/java/java-extension.yaml
          capture-prefix: java
          run: $PIPELINER examples/ipc/java/java-extension.yaml
        - name: examples/ipc/js/js-extension.yaml
          capture-prefix: js
          run: $PIPELINER examples/ipc/js/js-extension.yaml
        - name: examples/ipc/kotlin/kotlin-extension.yaml
          capture-prefix: kotlin
          run: $PIPELINER examples/ipc/kotlin/kotlin-extension.yaml
        - name: examples/ipc/lua/lua-extension.yaml
          capture-prefix: lua
          run: $PIPELINER examples/ipc/lua/lua-extension.yaml
        - name: examples/ipc/python/python-extension.yaml
          capture-prefix: python
          run: $PIPELINER examples/ipc/python/python-extension.yaml
        - name: examples/ipc/rust/rust-extension.yaml
          capture-prefix: rust
          run: $PIPELINER examples/ipc/rust/rust-extension.yaml
        - name: Echo Captured Properties
          run: |
            echo captured extension property \${{ bash.extension.property.1 }} = "${{ bash.extension.property.1 }}"
            echo captured extension property \${{ bash.extension.property.2 }} = "${{ bash.extension.property.2 }}"
            echo captured extension property \${{ csharp.extension.property.1 }} = "${{ csharp.extension.property.1 }}"
            echo captured extension property \${{ csharp.extension.property.2 }} = "${{ csharp.extension.property.2 }}"
            echo captured extension property \${{ go.extension.property.1 }} = "${{ go.extension.property.1 }}"
            echo captured extension property \${{ go.extension.property.2 }} = "${{ go.extension.property.2 }}"
            echo captured extension property \${{ groovy.extension.property.1 }} = "${{ groovy.extension.property.1 }}"
            echo captured extension property \${{ groovy.extension.property.2 }} = "${{ groovy.extension.property.2 }}"
            echo captured extension property \${{ java.extension.property.1 }} = "${{ java.extension.property.1 }}"
            echo captured extension property \${{ java.extension.property.2 }} = "${{ java.extension.property.2 }}"
            echo captured extension property \${{ js.extension.property.1 }} = "${{ js.extension.property.1 }}"
            echo captured extension property \${{ js.extension.property.2 }} = "${{ js.extension.property.2 }}"
            echo captured extension property \${{ kotlin.extension.property.1 }} = "${{ kotlin.extension.property.1 }}"
            echo captured extension property \${{ kotlin.extension.property.2 }} = "${{ kotlin.extension.property.2 }}"
            echo captured extension property \${{ lua.extension.property.1 }} = "${{ lua.extension.property.1 }}"
            echo captured extension property \${{ lua.extension.property.2 }} = "${{ lua.extension.property.2 }}"
            echo captured extension property \${{ python.extension.property.1 }} = "${{ python.extension.property.1 }}"
            echo captured extension property \${{ python.extension.property.2 }} = "${{ python.extension.property.2 }}"
            echo captured extension property \${{ rust.extension.property.1 }} = "${{ rust.extension.property.1 }}"
            echo captured extension property \${{ rust.extension.property.2 }} = "${{ rust.extension.property.2 }}"
