pipeline:
  name: Hello World C# Pipeline
  jobs:
    - name: Hello World C# Job
      working-directory: examples/ipc/c#
      steps:
        - name: Hello World C# Step
          with:
            name: Test User
          run: |
            rm -Rf extension
            rm -Rf extension.dll
            rm -Rf TMP
            mkdir TMP
            cd TMP && dotnet new console -n extension
            rm -Rf TMP/extension/Program.cs
            cp extension.cs TMP/extension/.
            cd TMP/extension && dotnet build -o extension
            cp ./TMP/extension/extension/extension ./extension
            cp ./TMP/extension/extension/extension.dll ./extension.dll
            cp ./TMP/extension/extension/extension.runtimeconfig.json ./extension.runtimeconfig.json
            rm -Rf TMP
            ./extension
        - name: Hello World C# Output Variables
          run: |
            echo output extension property \${{ extension_property_1 }} = "${{ extension_property_1 }}"
            echo output extension property \${{ extension_property_2 }} = "${{ extension_property_2 }}"
