pipeline:
  name: Hello World Java Pipeline
  jobs:
    - name: Hello World Java Job
      working-directory: examples/ipc/java
      steps:
        - name: Hello World Java Step
          shell: none
          with:
            name: Test User
          run: |
            javac Extension.java
            java -cp . Extension
        - name: Hello World Java Output Variables
          run: |
            echo output extension variable \${{ extension_variable_1 }} = "${{ extension_variable_1 }}"
            echo output extension variable \${{ extension_variable_2 }} = "${{ extension_variable_2 }}"
