pipeline:
  name: Hello World Bash Pipeline
  jobs:
    - name: Hello World Bash Job
      working-directory: examples/ipc/bash
      steps:
        - name: Hello World Bash Step
          shell: none
          with:
            name: Test User
          run: extension.sh
        - name: Hello World Bash Output Variables
          run: |
            echo output extension property \${{ extension_property_1 }} = "${{ extension_property_1 }}"
            echo output extension property \${{ extension_property_2 }} = "${{ extension_property_2 }}"
