pipeline:
  name: Hello World Bash Pipeline
  jobs:
    - name: Hello World Bash Job
      working-directory: examples/ipc/bash
      steps:
        - name: Hello World Bash Step
          shell: none
          with:
            name: Test User
          run: extension.sh
        - name: Hello World Bash Captured Properties
          run: |
            # The extension.property.1 was last set by the Rust extension
            echo captured extension property "\${{ extension.property.1 }}" = "${{ extension.property.1 }}"
            # The extension.property.2 was last set by the Rust extension
            echo captured extension property "\${{ extension.property.2 }}" = "${{ extension.property.2 }}"
