pipeline:
  name: Hello World Bash Pipeline
  jobs:
    - name: Hello World Bash Job
      working-directory: examples/ipc/bash
      steps:
        - name: Hello World Bash Step
          shell: none
          with:
            name: Test User
          run: extension.sh
        - name: Hello World Bash Captured Variables
          run: |
            # The extension_variable_1 was last set by the Rust extension
            echo captured extension variable "\${{ extension_variable_1 }}" = "${{ extension_variable_1 }}"
            # The extension_variable_2 was last set by the Rust extension
            echo captured extension variable "\${{ extension_variable_2 }}" = "${{ extension_variable_2 }}"
