pipeline:
  name: Hello World Go Pipeline
  jobs:
    - name: Hello World Go Job
      working-directory: examples/ipc/go
      steps:
        - name: Hello World Go Step
          shell: none
          with:
            name: Test User
          run: |
            go build extension.go
            ./extension
        - name: Hello World Go Output Variables
          run: |
            echo output extension property \${{ extension_property_1 }} = "${{ extension_property_1 }}"
            echo output extension property \${{ extension_property_2 }} = "${{ extension_property_2 }}"
