pipeline:
  name: Hello World Go Pipeline
  jobs:
    - name: Hello World Go Job
      working-directory: examples/ipc/go
      steps:
        - name: Hello World Go Step
          shell: none
          with:
            name: User
          run: Extension
        - name: Hello World Go Captured Properties
          run: |
            echo captured extension property \${{ extension.property.1 }} = "${{ extension.property.1 }}"
            echo captured extension property \${{ extension.property.2 }} = "${{ extension.property.2 }}"
