pipeline:
  name: Hello World Go Pipeline
  jobs:
    - name: Hello World Go Job
      working-directory: examples/ipc/go
      steps:
        - name: Hello World Go Step
          shell: none
          with:
            name: Test User
          run: |
            go build extension.go
            ./extension
        - name: Hello World Go Captured Variables
          run: |
            echo captured extension variable \${{ extension_variable_1 }} = "${{ extension_variable_1 }}"
            echo captured extension variable \${{ extension_variable_2 }} = "${{ extension_variable_2 }}"
