pipeline:
  name: Hello World Pipeline
  id: hello-world-pipeline
  enabled: true
  jobs:
    - name: Hello World Job
      id: hello-world-job
      enabled: true
      steps:
        - name: Hello World Step
          id: hello-world-step
          enabled: true
          run: echo "Hello World"