pipeline:
  name: checksum
  jobs:
    - name: job-1
      steps:
        - name: step-1
          with:
            filename: hello-world.txt
          run: |
            # Create a file
            echo -n "Hello World" > ${{ filename }}
            # SHA-1 checksum
            --sha-checksum ${{ filename }} 0a4d55a8d778e5022fab701977c5d840bbc486d0
            # SHA-256 checksum
            --sha-checksum ${{ filename }} a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e
            # SHA-512 checksum
            --sha-checksum ${{ filename }} 2c74fd17edafd80e8447b0d46741ee243b7eb74dd2149a0ab1b9246fb30382f27e853d8585719e0e67cbda0daa8f51671064615d645ae27acb15bfb1447f459b
            # Delete the file
            rm -Rf ${{ filename }}
