pipeline:
  name: environment-variables
  enabled: true
  env:
    PROPERTY1: foo
    PROPERTY2: bar
  jobs:
    - name: environment-variables-job
      enabled: true
      steps:
        - name: environment-variables-step
          enabled: true
          with:
            pwd: $PWD
          run: |
            echo $PROPERTY1 $PROPERTY2
            echo $PWD
