pipeline:
  name: environment-variables-pipeline
  env:
    PROPERTY1: foo
    PROPERTY2: bar
  jobs:
    - name: job-1
      steps:
        - name: step-1
          with:
            pwd: $PWD
          run: |
            echo $PROPERTY1 $PROPERTY2
            echo $PWD
