pipeline:
  id: environment-variables-pipeline
  enabled: true
  env:
    PROPERTY1: foo
    PROPERTY2: bar
  jobs:
    - id: environment-variables-job
      enabled: true
      steps:
        - id: environment-variables-step-1
          enabled: true
          with:
            pwd: $PWD
          run: |
            echo $PROPERTY1 $PROPERTY2
            echo $PWD
