pipeline:
  name: example-pipeline
  env:
    FOO: BAR
  with:
    global_property: Global Property - Pipeline
    pipeline_directory: .
    pipeline_property: Pipeline Property
  jobs:
    - name: example-pipeline-job
      enabled: true
      with:
        job_property: Job Property
        global_property: Global Property - Job
      steps:
        - name: pwd
          enabled: true
          run: pwd
        - name: ls -la | wc -l
          enabled: true
          run: ls -la | wc -l
        - name: echo-user
          enabled: true
          run: echo $USER
        - name: echo-pipeline-property
          enabled: true
          run: echo ${{ pipeline_property }}
        - name: echo-job-property
          enabled: true
          run: echo ${{ job_property }}
        - name: echo-step-property
          enabled: true
          with:
            step_property: Step Property
          run: echo "${{ pipeline_property }}" "${{ job_property }}" "${{ step_property }}"
        - name: echo-environment-variable
          enabled: true
          run: echo $FOO
        - name: echo-environment-variable-2
          enabled: true
          run: echo $FOO
        - name: run-multiple-commands
          enabled: true
          run: |
            pwd
            du -h -s
