pipeline:
  env:
    FOO: BAR
  with:
    global_property: Global Property - Pipeline
    pipeline_directory: .
    pipeline_property: Pipeline Property
  jobs:
    - enabled: true
      with:
        job_property: Job Property
        global_property: Global Property - Job
      steps:
        - enabled: true
          run: pwd
        - enabled: true
          run: ls -la | wc -l
        - enabled: true
          run: echo $USER
        - enabled: true
          run: echo ${{ pipeline_property }}
        - enabled: true
          run: echo ${{ job_property }}
        - enabled: true
          with:
            step_property: Step Property
          run: echo "${{ pipeline_property }}" "${{ job_property }}" "${{ step_property }}"
        - enabled: true
          run: echo $FOO
        - enabled: true
          run: echo $FOO
        - enabled: true
          run: |
            pwd
            du -h -s
