pipeline:
  name: example-pipeline
  env:
    FOO: BAR
  with:
    global.property: Global Property - Pipeline
    pipeline.directory: .
    pipeline.property: Pipeline Property
  jobs:
    - name: job-1
      enabled: true
      with:
        job.property: Job Property
        global.property: Global Property - Job
      steps:
        - name: pwd
          enabled: true
          run: pwd
        - name: ls -la
          enabled: true
          run: ls -la
        - name: echo-user
          enabled: true
          run: echo $USER
        - name: echo-pipeline-property
          enabled: true
          run: echo ${{ pipeline.property }}
        - name: echo-job-property
          enabled: true
          run: echo ${{ job.property }}
        - name: echo-step-property
          enabled: true
          with:
            step.property: Step Property
          run: echo "${{ pipeline.property }}" "${{ job.property }}" "${{ step.property }}"
        - name: echo-environment-variable
          enabled: true
          run: echo $FOO
        - name: echo-environment-variable-2
          enabled: true
          run: echo $FOO
        - name: run-multiple-commands
          enabled: true
          run: |
            pwd
            du -h -s
