pipeline:
  id: example-pipeline
  env:
    FOO: BAR
  with:
    global_variable: Global Variable - Pipeline
    pipeline_directory: .
    pipeline_variable: Pipeline Variable
  jobs:
    - id: example-pipeline-job
      enabled: true
      with:
        job_variable: Job Variable
        global_variable: Global Variable - Job
      steps:
        - id: example-pipeline-job-step-1
          enabled: true
          run: pwd
        - id: example-pipeline-job-step-2
          enabled: true
          run: ls -la | wc -l
        - id: example-pipeline-job-step-3
          enabled: true
          run: echo $USER
        - id: example-pipeline-job-step-4
          enabled: true
          run: echo ${{ pipeline_variable }}
        - id: example-pipeline-job-step-5
          enabled: true
          run: echo ${{ job_variable }}
        - id: example-pipeline-job-step-6
          enabled: true
          with:
            step_variable: Step Variable
          run: echo "${{ pipeline_variable }}" "${{ job_variable }}" "${{ step_variable }}"
        - id: example-pipeline-job-step-7
          enabled: true
          run: echo $FOO
        - id: example-pipeline-job-step-8
          enabled: true
          run: echo $FOO
        - id: example-pipeline-job-step-9
          enabled: true
          run: |
            pwd
            du -h -s
