pipeline:
  name: example-pipeline
  env:
    FOO: BAR
  with:
    global_variable: Global Variable - Pipeline
    pipeline_directory: .
    pipeline_variable: Pipeline Variable
  jobs:
    - name: job-1
      with:
        job_variable: Job Variable
        global_variable: Global Variable - Job
      steps:
        - name: step-1
          run: |
            pwd
        - name: step-2
          run: |
            ls -la | wc -l
        - name: step-3
          enabled: true
          run: |
            echo $USER
        - name: step-4
          run: |
            echo ${{ pipeline_variable }}
        - name: step-5
          run: |
            echo ${{ job_variable }}
        - name: step-6
          with:
            step_variable: Step Variable
          run: |
            echo "${{ pipeline_variable }}" "${{ job_variable }}" "${{ step_variable }}"
        - name: step-8
          run: |
            echo $FOO
        - name: step-9
          run: |
            echo $FOO
        - name: step-10
          run: |
            pwd
            du -h -s
