pipeline:
  env:
    FOO: BAR
  with:
    global_variable: Global Variable - Pipeline
    pipeline_directory: .
    pipeline_variable: Pipeline Variable
  jobs:
    - enabled: true
      with:
        job_variable: Job Variable
        global_variable: Global Variable - Job
      steps:
        - enabled: true
          run: pwd
        - enabled: true
          run: ls -la | wc -l
        - enabled: true
          run: echo $USER
        - enabled: true
          run: echo ${{ pipeline_variable }}
        - enabled: true
          run: echo ${{ job_variable }}
        - enabled: true
          with:
            step_variable: Step Variable
          run: echo "${{ pipeline_variable }}" "${{ job_variable }}" "${{ step_variable }}"
        - enabled: true
          run: echo $FOO
        - enabled: true
          run: echo $FOO
        - enabled: true
          run: |
            pwd
            du -h -s
