pipeline:
  id: example-pipeline
  env:
    FOO: BAR
  with:
    global_property: Global Property - Pipeline
    pipeline_directory: .
    pipeline_property: Pipeline Property
  jobs:
    - id: example-pipeline-job
      enabled: true
      with:
        job_property: Job Property
        global_property: Global Property - Job
      steps:
        - id: example-pipeline-job-step-1
          enabled: true
          run: pwd
        - id: example-pipeline-job-step-2
          enabled: true
          run: ls -la | wc -l
        - id: example-pipeline-job-step-3
          enabled: true
          run: echo $USER
        - id: example-pipeline-job-step-4
          enabled: true
          run: echo ${{ pipeline_property }}
        - id: example-pipeline-job-step-5
          enabled: true
          run: echo ${{ job_property }}
        - id: example-pipeline-job-step-6
          enabled: true
          with:
            step_property: Step Property
          run: echo "${{ pipeline_property }}" "${{ job_property }}" "${{ step_property }}"
        - id: example-pipeline-job-step-7
          enabled: true
          run: echo $FOO
        - id: example-pipeline-job-step-8
          enabled: true
          run: echo $FOO
        - id: example-pipeline-job-step-9
          enabled: true
          run: |
            pwd
            du -h -s
