pipeline:
  name: extensions
  jobs:
    - name: job-1
      steps:
        - name: step-1
          run: |
            mkdir -p TMP
            rm -Rf TMP/*
            echo "#!/bin/bash" > TMP/run.sh
            echo "" >> TMP/run.sh
            echo "echo This is an example extension" >> TMP/run.sh
            echo "" >> TMP/run.sh
            cd TMP && zip -qr tmp.zip *
        - name: step-2
          run: |
            echo $PIPELINER_HOME/TMP/tmp.zip
            --extension $PIPELINER_HOME/TMP/tmp.zip
        - name: step-3
          enabled: false
          with:
            extension_zip: $PIPELINER_HOME/TMP/tmp.zip
          run: |
            --extension ${{ extension_zip }}
        - name: step-4
          enabled: false
          run: |
            rm -Rf TMP
