pipeline:
  name: extensions
  enabled: true
  jobs:
    - name: extensions-job
      steps:
        - name: Create Example Extension
          run: |
            mkdir -p TMP
            rm -Rf TMP/*
            echo "echo executing example extension" > TMP/execute.sh
            cd TMP && zip -qr tmp.zip *
        - name: Execute Example Extension 1
          run: --extension file://TMP/tmp.zip
        - name: Execute Example Extension 2
          run: --extension TMP/tmp.zip
        - name: Delete Example Extension
          run: rm -Rf TMP
        - name: Execute Remote Extension
          enabled: false
          # Example using extension downloaded from an HTTP server with username, password, connection timeout and read timeout
          with:
            pipeliner_extension_http_username: my-username
            pipeliner_extension_http_password: my-password
            pipeliner_extension_http_connect_timeout: 30000 # 30 seconds
            pipeliner_extension_http_read_timeout: 30000 # 30 seconds
          # Example using extension downloaded from an HTTP server
          run: --extension http://<YOUR_SERVER>/tmp.zip
