pipeline:
  name: Extensions Pipeline
  id: extensions-pipeline
  enabled: true
  jobs:
    - name: Extensions Job
      id: extensions-job
      steps:
        - name: Create Example Extension
          id: create-example-extension
          run: |
            mkdir -p TMP
            rm -Rf TMP/*
            echo "echo executing example extension" > TMP/execute.sh
            cd TMP && zip -qr tmp.zip *
        - name: Execute Example Extension 1
          id: execute-example-extension-1
          run: --extension file://TMP/tmp.zip
        - name: Execute Example Extension 2
          id: execute-example-extension-2
          run: --extension TMP/tmp.zip
        - name: Delete Example Extension
          id: delete-example-extension
          run: rm -Rf TMP
        - name: Execute Remote Extension
          id: execute-remote-extension
          enabled: false
          # Example using extension downloaded from an HTTP server with username, password, connection timeout and read timeout
          with:
            pipeliner.extension.http.username: my-username
            pipeliner.extension.http.password: my-password
            pipeliner.extension.http.connect.timeout: 30000 # 30 seconds
            pipeliner.extension.http.read.timeout: 30000 # 30 seconds
          # Example using extension downloaded from an HTTP server
          run: --extension http://<YOUR_SERVER>/tmp.zip
