pipeline:
  name: Ipc Pipeline
  jobs:
    - name: Ipc Job
      steps:
        - name: Ipc Step 1
          id: ipc-step-1
          with:
            property.1: step.foo
            property.2: step.bar
          run: java -cp target/verifyica-pipeliner.jar org.verifyica.pipeliner.extension.Extension
        - name: Ipc Step 2
          run: |
            echo global property ${{ extension.property.1 }}
            echo global property ${{ extension.property.2 }}
            echo scoped property ${{ ipc-step-1.extension.property.1 }}
            echo scoped property ${{ ipc-step-1.extension.property.2 }}
            
