pipeline:
  id: mask-commands-pipeline
  with:
    pipeliner_mask_commands: true
  jobs:
    - id: mask-commands-job
      enabled: true
      steps:
        - id: mask-commands-step-1
          enabled: true
          run: |
            echo pipeliner_mask_commands = \"${{ pipeliner_mask_commands }}\"
        - id: mask-commands-step-2
          enabled: true
          with:
            pipeliner_mask_commands: false
          run: |
            echo pipeliner_mask_commands = \"${{ pipeliner_mask_commands }}\"
        - id: mask-commands-step-3
          enabled: true
          run: |
            echo pipeliner_mask_commands = \"${{ pipeliner_mask_commands }}\"
