pipeline:
  name: pipeline
  description: Print Directive pipeline
  env:
    GLOBAL: global
  jobs:
    - name: job
      steps:
        - name: step-1
          with:
            user: user
            server: some.server
            user_server: ${{ user }}@${{ server }}
          run: |
            --print:info define variables
        - name: step-2
          run: |
            --print:info \$GLOBAL = "$GLOBAL"
            --print:info \${GLOBAL} = "${GLOBAL}"
            --print:info \${{ user }} = "${{ user }}"
            --print:info \${{ server }} = "${{ server }}"
            --print:info \${{ user_server }} = "${{ user_server }}"
            --print:warning A warning message
            --print:error An error message
