pipeline:
  name: Hello World Pipeline
  id: hello-world-pipeline
  enabled: true
  with:
    property.1: pipeline.foo
    property.2: pipeline.bar
  jobs:
    - name: Hello World Job
      id: hello-world-job
      enabled: true
      with:
        property.1: ${{ hello-world-pipeline.property.1 }}_job.foo
        property.2: ${{ hello-world-pipeline.property.2 }}_job.bar
      steps:
        - name: Hello World Step
          id: hello-world-step
          enabled: true
          with:
            property.1: ${{ hello-world-job.property.1 }}_step.foo
            property.2: ${{ hello-world-job.property.2 }}_step.bar
          run: |
            echo globally scope properties - ${{ property.1 }} ${{ property.2 }}
            echo step scoped properties - ${{ hello-world-step.property.1 }} ${{ hello-world-step.property.2 }}
            echo job scoped properties - ${{ hello-world-job.hello-world-step.property.1 }} ${{ hello-world-job.hello-world-step.property.2 }}
            echo pipeline scoped properties - ${{ hello-world-pipeline.hello-world-job.hello-world-step.property.1 }} ${{ hello-world-pipeline.hello-world-job.hello-world-step.property.2 }}
