pipeline:
  name: properties-1
  enabled: true
  with:
    property.1: pipeline.foo
    property.2: pipeline.bar
    pipeline.property.1: pipeline.foo
    pipeline.property.2: pipeline.bar
  jobs:
    - name: properties-1-job
      enabled: true
      with:
        property.1: job.foo
        property.2: job.bar
        job.property.1: job.foo
        job.property.2: job.bar
      steps:
        - name: properties-1-step
          enabled: true
          with:
            property.1: step.foo
            property.2: step.bar
            step.property.1: step.foo
            step.property.2: step.bar
          run: |
            # echo's the last value of propert.1 and property.2
            echo globally scoped properties = ${{ property.1 }} ${{ property.2 }}
            # echo's the last value of pipeline.property.1 and pipeline.property.2
            echo pipeline scoped properties = ${{ pipeline.property.1 }} ${{ pipeline.property.2 }}
            # echo's the last value of job.property.1 and job.property.2
            echo job scoped properties = ${{ job.property.1 }} ${{ job.property.2 }}
            # echo's the last value of step.property.1 and step.property.2
            echo step scoped properties = ${{ step.property.1 }} ${{ step.property.2 }}
