pipeline:
  name: Hello World Pipeline
  id: hello-world-pipeline
  enabled: true
  with:
    property.1: foo
    property.2: bar
  jobs:
    - name: Hello World Job
      id: hello-world-job
      enabled: true
      steps:
        - name: Hello World Step
          id: hello-world-step
          enabled: true
          run: echo ${{ property.1 }} ${{ property.2 }}
