pipeline:
  name: Hello World Pipeline
  id: hello-world-pipeline
  enabled: true
  with:
    property_1: pipeline.foo
    property_2: pipeline.bar
  jobs:
    - name: Hello World Job
      id: hello-world-job
      enabled: true
      with:
        property_1: job.foo
        property_2: job.bar
      steps:
        - name: Hello World Step
          id: hello-world-step
          enabled: true
          with:
            property_1: step.foo
            property_2: step.bar
          run: |
            echo globally scoped properties = ${{ property_1 }} ${{ property_2 }}
            echo step scoped properties = ${{ hello-world-step.property_1 }} ${{ hello-world-step.property_2 }}
            echo step scope properties = ${{ hello-world-job.hello-world-step.property_1 }} ${{ hello-world-job.hello-world-step.property_2 }}
            echo step scoped properties = ${{ hello-world-pipeline.hello-world-job.hello-world-step.property_1 }} ${{ hello-world-pipeline.hello-world-job.hello-world-step.property_2 }}
            echo job scoped properties = ${{ hello-world-job.property_1 }} ${{ hello-world-job.property_2 }}
            echo job scoped properties = ${{ hello-world-pipeline.hello-world-job.property_1 }} ${{ hello-world-pipeline.hello-world-job.property_2 }}
            echo pipeline scoped properties = ${{ hello-world-pipeline.property_1 }} ${{ hello-world-pipeline.property_2 }}
