pipeline:
  name: Hello World Pipeline
  enabled: true
  jobs:
    - name: Hello World Job
      enabled: true
      steps:
        - id: variables
          name: Define variables
          env:
            TEST_VARIABLE_1: env test variable 1
          with:
            test_variable_1: test variable 1
          # No run command, just define variables
        - name: Hello World Step 1
          id: hello-world-step-1
          enabled: true
          with:
            variable_1: step 1 variable 1
            variable_2: step 1 variable 2
          run: |
            echo "\${{ variable_1 }}" = \"${{ variable_1 }}\"
            echo "\${{ variable_2 }}" = \"${{ variable_2 }}\"
        - name: Hello World Step 2
          id: hello-world-step-2
          enabled: true
          with:
            variable_1: step 2 variable 1
            variable_2: step 2 variable 2
          run: |
            echo "\${{ variable_1 }}" = \"${{ variable_1 }}\"
            echo "\${{ variable_2 }}" = \"${{ variable_2 }}\"
        - name: Hello World Step 3
          id: hello-world-step-3
          enabled: true
          run: |
            echo "\$TEST_VARIABLE_1" = \"$TEST_VARIABLE_1\"
            echo "\${TEST_VARIABLE_1}" = \"${TEST_VARIABLE_1}\"
            echo "\${{ test_variable_1 }}" = \"${{ test_variable_1 }}\"
            echo "\${{ variables.test_variable_1 }}" = \"${{ variables.test_variable_1 }}\"
            echo "\${{ hello-world-step-1.variable_1 }}" = \"${{ hello-world-step-1.variable_1 }}\"
            echo "\${{ hello-world-step-1.variable_2 }}" = \"${{ hello-world-step-1.variable_2 }}\"
            echo "\${{ hello-world-step-2.variable_1 }}" = \"${{ hello-world-step-2.variable_1 }}\"
            echo "\${{ hello-world-step-2.variable_2 }}" = \"${{ hello-world-step-2.variable_2 }}\"
        - name: Reset variables
          env:
            TEST_VARIABLE_1: ""
          with:
            test_variable_1: ""
          # No run command, just reset variables
        - name: Hello World Step 4
          enabled: true
          run: |
            echo "\$TEST_VARIABLE_1" = \"$TEST_VARIABLE_1\"
            echo "\${TEST_VARIABLE_1}" = \"${TEST_VARIABLE_1}\"
            echo "\${{ test_variable_1 }}" = \"${{ test_variable_1 }}\"
            # By design, variables.test_variable_1 is not cleared
            echo "\${{ variables.test_variable_1 }}" = \"${{ variables.test_variable_1 }}\"
