pipeline:
  name: Hello World Pipeline
  enabled: true
  with:
    property_1: pipeline.foo
    property_2: pipeline.bar
  jobs:
    - name: Hello World Job
      enabled: true
      with:
        property_1: job.foo
        property_2: job.bar
      steps:
        - name: Hello World Step
          enabled: true
          with:
            property_1: step.foo
            property_2: step.bar
          run: |
            echo globally scoped properties = ${{ property_1 }} ${{ property_2 }}
