pipeline:
  name: Variables Pipeline
  enabled: true
  with:
    variable_1: pipeline.foo
    variable_2: pipeline.bar
    pipeline.variable_1: pipeline.foo
    pipeline.variable_2: pipeline.bar
  jobs:
    - name: Variables Job
      enabled: true
      with:
        variable_1: job.foo
        variable_2: job.bar
        job.variable_1: job.foo
        job.variable_2: job.bar
      steps:
        - name: Variables Step
          enabled: true
          with:
            variable_1: step.foo
            variable_2: step.bar
            step.variable_1: step.foo
            step.variable_2: step.bar
          run: |
            echo variables = ${{ pipeline.variable_1 }} ${{ pipeline.variable_2 }}
            echo variables = ${{ job.variable_1 }} ${{ job.variable_2 }}
            echo variables = ${{ step.variable_1 }} ${{ step.variable_2 }}
            echo variables = ${{ variable_1 }} ${{ variable_2 }}
