pipeline:
  name: Hello World Pipeline
  enabled: true
  with:
    variable_1: pipeline.foo
    variable_2: pipeline.bar
  jobs:
    - name: Hello World Job
      enabled: true
      with:
        variable_1: job.foo
        variable_2: job.bar
      steps:
        - name: Hello World Step
          enabled: true
          with:
            variable_1: step.foo
            variable_2: step.bar
          run: |
            echo globally scoped variables = ${{ variable_1 }} ${{ variable_2 }}
