pipeline:
  name: Hello World Pipeline
  id: hello-world-pipeline
  enabled: true
  with:
    variable_1: pipeline.foo
    variable_2: pipeline.bar
  jobs:
    - name: Hello World Job
      id: hello-world-job
      enabled: true
      with:
        variable_1: ${{ hello-world-pipeline.variable_1 }}_job.foo
        variable_2: ${{ hello-world-pipeline.variable_2 }}_job.bar
      steps:
        - name: Hello World Step
          id: hello-world-step
          enabled: true
          with:
            variable_1: ${{ hello-world-job.variable_1 }}_step.foo
            variable_2: ${{ hello-world-job.variable_2 }}_step.bar
          run: |
            echo globally scope properties = ${{ variable_1 }} ${{ variable_2 }}
            echo step scoped variables = ${{ hello-world-step.variable_1 }} ${{ hello-world-step.variable_2 }}
            echo job scoped variables = ${{ hello-world-job.hello-world-step.variable_1 }} ${{ hello-world-job.hello-world-step.variable_2 }}
            echo pipeline scoped variables = ${{ hello-world-pipeline.hello-world-job.hello-world-step.variable_1 }} ${{ hello-world-pipeline.hello-world-job.hello-world-step.variable_2 }}
