pipeline:
  name: Hello World Groovy Pipeline
  jobs:
    - name: Hello World Groovy Job
      working-directory: examples/ipc/groovy
      steps:
        - name: Hello World Groovy Step
          shell: none
          with:
            name: Test User
          run: groovy extension.groovy
        - name: Hello World Groovy Captured Variables
          run: |
            echo captured extension variable \${{ extension_variable_1 }} = "${{ extension_variable_1 }}"
            echo captured extension variable \${{ extension_variable_2 }} = "${{ extension_variable_2 }}"
