pipeline:
  name: Hello World Groovy Pipeline
  jobs:
    - name: Hello World Groovy Job
      working-directory: examples/ipc/groovy
      steps:
        - name: Hello World Groovy Step
          shell: none
          with:
            name: Test User
          run: groovy extension.groovy
        - name: Hello World Groovy Output Variables
          run: |
            echo output extension property \${{ extension_property_1 }} = "${{ extension_property_1 }}"
            echo output extension property \${{ extension_property_2 }} = "${{ extension_property_2 }}"
