pipeline:
  name: Hello World JavaScript Pipeline
  jobs:
    - name: Hello World JavaScript Job
      working-directory: examples/ipc/js
      steps:
        - name: Hello World JavaScript Step
          shell: none
          with:
            name: Test User
          run: node extension.js
        - name: Hello World JavaScript Output Variables
          run: |
            echo output extension property \${{ extension_property_1 }} = "${{ extension_property_1 }}"
            echo output extension property \${{ extension_property_2 }} = "${{ extension_property_2 }}"
