pipeline:
  name: Hello World JavaScript Pipeline
  jobs:
    - name: Hello World JavaScript Job
      working-directory: examples/ipc/js
      steps:
        - name: Hello World JavaScript Step
          shell: none
          with:
            name: Test User
          run: node extension.js
        - name: Hello World JavaScript Captured Variables
          run: |
            echo captured extension variable \${{ extension_variable_1 }} = "${{ extension_variable_1 }}"
            echo captured extension variable \${{ extension_variable_2 }} = "${{ extension_variable_2 }}"
