name: Build
on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install zsh
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build
      run: ./mvnw -B clean verify
    - name: Package
      run: ./pipeliner package.yaml
