name: Build
permissions:
  contents: read
on:
  push:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.kt'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dash
      run: |
        sudo apt-get update
        sudo apt-get install -y dash
    - name: Install fish
      run: |
        sudo apt-get update
        sudo apt-get install -y fish
    - name: Install ksh
      run: |
        sudo apt-get update
        sudo apt-get install -y ksh
    - name: Install zsh
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh
    - name: Install zip
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build
      run: ./mvnw -B clean verify
    - name: Run Example
      run: ./pipeliner examples/example.plr
    - name: Run Package
      run: ./pipeliner package.plr
